name: Build and deploy app

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build WASM
      run: wasm-pack build
    - name: Build www
      run: npm run --prefix www build
    - uses: actions/upload-pages-artifact@v1.0.8
      with: 
        path: "www/dist/"
