name: Build and Deploy app

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build wasm
      run: wasm-pack build
    - name: install dev deps for www build
      working-directory: www
      run: npm i
    - name: Build www
      run: npm run --prefix www build
    - uses: actions/upload-pages-artifact@v1.0.8
      with: 
        path: "www/dist/"
